### ISSUE TITLE
Not running?

### ISSUE THREAD

**Issue by meza** [MyAlbum/purge-cache#5]
Hey,

I've just upgraded to v2 because v1 was having this exact same issue and it's still happening. Any ideas why?

<img width="1606" alt="image" src="https://github.com/MyAlbum/purge-cache/assets/211977/9c6930c1-5d6f-4072-9aa1-73c52c58510d">

I'm trying to run a very basic cache cleanup like this:

```yml
name: Clear Cache

permissions: write-all

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # Runs once a day (https://crontab.guru/once-a-day)
jobs:
  clear:
    name: Clear cache
    runs-on: ubuntu-latest
    steps:
      - uses: MyAlbum/purge-cache@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
          max-age: 259200 # Cache max 3 days since last use (this is the default)

```
