### ISSUE TITLE
Tag `@v2` does not point to latest version

### ISSUE THREAD

**Issue by olifre** [MyAlbum/purge-cache#7]
Trying the example from the documentation:
```yml
steps:
# Do other steps like checkout, install, compile, etc.
- uses: MyAlbum/purge-cache@v2
  with:
    accessed: true # Purge caches by their last accessed time (default)
    created: false # Purge caches by their created time (default)
    max-age: 604800 # Leave only caches accessed in the last 7 days (default)
```
fails, as the version available via the `@v2` tag does not yet support these arguments. 
Using `@v2.1.0` explicitly works fine, many thanks for this useful action!
